### PR TITLE
allow symfony 3

### PR DESCRIPTION
**Pull request by pjordaan**
Seems nothing was used that doesn't work in Symfony 3.

### CODE REVIEW

**Comment by nikophil** [comment]
+1

**Comment by nicoschoenmaker** [comment]
+1

**Comment by seballot** [comment]
+1, why this commit is not already pushed?

**Comment by bronek89** [comment]
+1

**Comment by MvanRietschoten** [comment]
+1

**Comment by MvanRietschoten** [comment]
I tried this... however this does break. As theDemoCompilationController extends ContainerAware and that does not exist anymore. Can you update your PR by using the ContainerAwareInterface?

**Comment by MvanRietschoten** [comment]
I've created a fork with the correct changes for symfony 3 compatibility in this branch: https://github.com/MvanRietschoten/JMSTwigJsBundle/tree/symfony3

You can temporarily add this to your composer:

``` json
"repositories": [
        {
            "type": "git",
            "url":  "https://github.com/MvanRietschoten/JMSTwigJsBundle.git"
        }
    ],
```

And:

``` json
"jms/twig-js-bundle": "dev-symfony3",
```

@pjordaan Can you update your pr with the correct changes? Or should I create a PR?

**Comment by pjordaan** [comment]
hm, I think I missed this PR. I guess I can close it.

**Pull request closed without merging**
