### PR TITLE
Add support for Symfony2.3 and correct some unit tests

### PR DESCRIPTION
**Pull request by franek**
I do need to change dependency from symfony/framework-bundle to symfony/symfony. It perhaps a bit dangerous but otherwise unit tests was failing (and for other errors)...

### CODE REVIEW

**Comment by natorojr** [comment]
Just tried upgrading to Symfony 2.3 stable release (which was announced today), but got these twig-js-bundle Composer errors:

jms/twig-js-bundle dev-master requires symfony/framework-bundle 2.*,<2.3 -> satisfiable by symfony/symfony[v2.2.1, 2.0.7, v2.0.10, v2.0.11, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.18, v2.0.19, v2.0.20, v2.0.21, v2.0.22, v2.0.23, v2.0.9, v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.2], symfony/framework-bundle[2.0.7, v2.0.10, v2.0.12, v2.0.13, v2.0.14, v2.0.15, v2.0.16, v2.0.17, v2.0.18, v2.0.19, v2.0.20, v2.0.21, v2.0.22, v2.0.23, v2.0.9, v2.1.0, v2.1.1, v2.1.10, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1].

Would be nice to get this fixed ASAP

**Comment by jvanbouchaute** [comment]
I concur, support for Symfony 2.3 is important because it's the Long-Term Support release.

**Comment by adam-lynch** [comment]
:+1:

**Comment by suncat2000** [comment]
+1

**Comment by jverdeyen** [comment]
:+1:

**Comment by bgintz** [comment]
+1

**Comment by stefk** [comment]
I was gone for +1 but actually, I don't understand why the dependency should be set to symfony/symfony, as the tests don't need the whole framework to be installed. I've made a simple pull request just for the upgrade (https://github.com/schmittjoh/JMSTwigJsBundle/pull/27). Other changes are interesting though.

**Comment by natorojr** [comment]
Looks like devs fixed the composer.json file today. I can now download with Composer and it seems to be working fine in my project.
Thanks!!

**Comment by franek** [comment]
stale PR ;)

**Pull request closed without merging**
